### ISSUE TITLE
Custom match patterns

### ISSUE THREAD

**Issue by monomadic** [gerardroche/sublime-sesame#4]
Great plugin, but is there any way to turn off recursive indexing? I have all my projects nested under ~/Projects/ but the autocomplete is finding things I don't really want, deep in the project folder hierarchy. It also won't let me open an empty folder.

**Comment by gerardroche** [comment]
Open Sesame lists projects one folder deep `~/Projects/*/*` i.e. by `vendor/name`. You'd like the option to list projects just one folder deep i.e. `~/Projects/*`?

**Comment by monomadic** [comment]
Ahhhh I didn't actually realise that, but all of my projects are my own, not vendor/name, just ~/Projects/name/

The behaviour makes a lot more sense now... but I wish I could change the match pattern :P

**Comment by gerardroche** [comment]
I'll add an option. I do recommend changing the way you organise your projects. I usually organise things based on github url `user/name`.

**Comment by monomadic** [comment]
Hey, thanks, but - these are all my own projects. I actually have another folder, ~/Projects/_cloned/ which contains all my vendor projects I contribute to or use. Most projects I work on daily are my own, so using a system like that would end up confusing and provide little benefit as I'd have to remember the vendor name!

**Comment by gerardroche** [comment]
Set `open-sesame.projects_depth` to 1.

**Comment by gerardroche** [comment]
btw I do something similar to how you handle vendor repositories except I put them all in a completely separate folder named ~/vendor and then have custom open sesame commands specifically for that directory.

```
[
    {
        "caption": "Open Sesame: Open Vendor",
        "command": "open_sesame",
        "args": { "path": "~/vendor" }
    },
    {
        "caption": "Open Sesame: Add Vendor",
        "command": "open_sesame_add_folder",
        "args": { "path": "~/vendor" }
    },
]
```

See https://github.com/gerardroche/sublimefiles/blob/master/User/Default.sublime-commands

**Comment by monomadic** [comment]
tested, works great! thanks so much!!!
