### ISSUE TITLE
Can not open folders that have a pipe in the name

### ISSUE THREAD

**Issue by danieldiekmeier** [gerardroche/sublime-sesame#6]
First of: Thanks for Open Sesame, it's a great idea and a nice plugin! :)

One thing, though: Most of my project folders have a `|` pipe symbol in the name, for example `EN | 2017 | Project` (I know, it's terrible, but my employer chose this ¯\_(ツ)_/¯), and these Folders do not show up in the Open Sesame overview.

Can this be fixed? <3

**Comment by gerardroche** [comment]
Your employer is a maniac.

**Comment by danieldiekmeier** [comment]
Thank you so much! :)
